# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20180630_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='todos.Todo'),
        ),
    ]
