# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sub_task',
            field=models.BooleanField(default=False),
        ),
    ]
